"""Writes the shared tables in src/spec_tables.h from data/ and pret's formulas.

usage: generate_spec_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
import unicodedata
from pathlib import Path

LANGUAGE_COLUMNS = [
    "japanese",
    "english",
    "french",
    "italian",
    "german",
    "spanish",
    "korean",
    "chinese_simplified",
    "chinese_traditional",
]
# Latin names change case; Japanese, Korean and Chinese ones have none.
CASELESS_COLUMNS = ["japanese", "korean", "chinese_simplified", "chinese_traditional"]
GROWTH_RATES = ["medium_fast", "erratic", "fluctuating", "medium_slow", "fast", "slow"]
MAX_LEVEL = 100
NAME_KINDS = [
    ("move", "SPEC_MOVE_NAME_COUNT"),
    ("ability", "SPEC_ABILITY_NAME_COUNT"),
    ("item", "SPEC_ITEM_NAME_COUNT"),
    ("nature", "SPEC_NATURE_COUNT"),
    ("type", "SPEC_TYPE_COUNT"),
]


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_spec_tables.py from {source}; do not edit.\n"
    header += '#include "spec_tables.h"\n\n'
    path.write_text(header + body)


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def without_accents(text):
    return "".join(ch for ch in unicodedata.normalize("NFD", text) if unicodedata.category(ch) != "Mn")


# As Gen 3 and 4 store them: Latin names in upper case, and French ones without accents.
def upper_case_name(name, language):
    if language in CASELESS_COLUMNS:
        return name
    if language == "french":
        return unicodedata.normalize("NFC", without_accents(name.upper()))
    return name.upper()


# As Gen 1 and 2 store them: as Gen 3 and 4 do, but with no space in Mr. Mime's name.
def game_boy_name(name, language):
    return upper_case_name(name, language).replace(". ", ".")


# As Gen 5 stores them: Farfetch'd with a plain apostrophe.
def gen5_name(name, language):
    return name.replace("\u2019", "'")


def species_names_body(species_names, table_name, name_of):
    lines = [f"const char *const {table_name}[SPEC_NAME_LANGUAGE_COUNT][SPEC_SPECIES_NAME_COUNT] = {{"]
    for language in LANGUAGE_COLUMNS:
        lines.append(f"    [SPEC_LANGUAGE_{language.upper()}] = {{")
        for row in species_names:
            lines.append(f"        [{row['national']}] = {c_string(name_of(row[language], language))},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


# The other name tables: a row per number, a column per language, "-" for no name.
def names_body(rows, number_column, table_name, count_name):
    lines = [f"const char *const {table_name}[SPEC_NAME_LANGUAGE_COUNT][{count_name}] = {{"]
    for language in LANGUAGE_COLUMNS:
        lines.append(f"    [SPEC_LANGUAGE_{language.upper()}] = {{")
        for row in rows:
            if row[language] != "-":
                lines.append(f"        [{row[number_column]}] = {c_string(row[language])},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


# "-" is every game, which the first game type stands for.
def from_game_enum(from_game):
    return "SPEC_GAME_TYPE_" + ("red_blue" if from_game == "-" else from_game).upper()


def form_names_body(rows):
    lines = ["const spec_form_names_t spec_form_names[] = {"]
    for row in rows:
        lines.append(f"    {{{row['national']}, {row['form']}, {from_game_enum(row['from_game'])}, {{")
        for language in LANGUAGE_COLUMNS:
            if row[language] != "-":
                lines.append(f"        [SPEC_LANGUAGE_{language.upper()}] = {c_string(row[language])},")
        lines.append("    }},")
    lines.append("};\n")
    lines.append("const size_t spec_form_names_count = sizeof spec_form_names / sizeof spec_form_names[0];")
    return "\n".join(lines) + "\n"


def game_limits_body(rows):
    lines = ["const spec_game_limits_t spec_game_limits[SPEC_GAME_TYPE_COUNT] = {"]
    for row in rows:
        limits = f"{row['last_species']}, {row['last_move']}, {row['last_ability']}"
        lines.append(f"    [SPEC_GAME_TYPE_{row['game'].upper()}] = {{{limits}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def move_data_body(rows):
    lines = ["const spec_move_data_row_t spec_move_data_rows[] = {"]
    for row in rows:
        move_data = f"{{SPEC_TYPE_{row['type'].upper()}, {row['pp']}}}"
        lines.append(f"    {{{row['move']}, {from_game_enum(row['from_game'])}, {move_data}}},")
    lines.append("};\n")
    lines.append("const size_t spec_move_data_row_count =")
    lines.append("    sizeof spec_move_data_rows / sizeof spec_move_data_rows[0];")
    return "\n".join(lines) + "\n"


def growth_rate_enum(name):
    return "SPEC_GROWTH_RATE_" + name.upper()


def experience_at_level(growth_rate, n):
    # pret's experience_tables.h lists levels 0 and 1 outright and uses these formulas from level 2.
    if n <= 1:
        return n
    cube = n * n * n
    if growth_rate == "medium_fast":
        return cube
    if growth_rate == "erratic":
        if n <= 50:
            return (100 - n) * cube // 50
        if n <= 68:
            return (150 - n) * cube // 100
        if n <= 98:
            return ((1911 - 10 * n) // 3) * cube // 500
        return (160 - n) * cube // 100
    if growth_rate == "fluctuating":
        if n <= 15:
            return ((n + 1) // 3 + 24) * cube // 50
        if n <= 36:
            return (n + 14) * cube // 50
        return ((n // 2) + 32) * cube // 50
    if growth_rate == "medium_slow":
        return (6 * cube) // 5 - 15 * n * n + 100 * n - 140
    if growth_rate == "fast":
        return (4 * cube) // 5
    if growth_rate == "slow":
        return (5 * cube) // 4
    raise ValueError(growth_rate)


def experience_body():
    lines = ["const uint32_t spec_experience[SPEC_GROWTH_RATE_COUNT][SPEC_LEVEL_COUNT] = {"]
    for growth_rate in GROWTH_RATES:
        values = [str(experience_at_level(growth_rate, level)) for level in range(MAX_LEVEL + 1)]
        lines.append(f"    [{growth_rate_enum(growth_rate)}] = {{")
        for start in range(0, len(values), 10):
            lines.append("        " + ", ".join(values[start : start + 10]) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species_names = read_tsv(data_directory / "species_names.tsv")
    names = species_names_body(species_names, "spec_species_names", lambda name, language: name)
    names += "\n" + species_names_body(species_names, "spec_game_boy_species_names", game_boy_name)
    names += "\n" + species_names_body(species_names, "spec_upper_case_species_names", upper_case_name)
    names += "\n" + species_names_body(species_names, "spec_gen5_species_names", gen5_name)
    write_c_file(output_directory / "species_names.c", "data/species_names.tsv", names)
    forms = form_names_body(read_tsv(data_directory / "form_names.tsv"))
    write_c_file(output_directory / "form_names.c", "data/form_names.tsv", forms)
    for kind, count_name in NAME_KINDS:
        rows = read_tsv(data_directory / f"{kind}_names.tsv")
        body = names_body(rows, kind, f"spec_{kind}_names", count_name)
        write_c_file(output_directory / f"{kind}_names.c", f"data/{kind}_names.tsv", body)
    limits = game_limits_body(read_tsv(data_directory / "game_limits.tsv"))
    write_c_file(output_directory / "game_limits.c", "data/game_limits.tsv", limits)
    moves = move_data_body(read_tsv(data_directory / "moves.tsv"))
    write_c_file(output_directory / "move_data.c", "data/moves.tsv", moves)
    write_c_file(output_directory / "experience.c", "pret's growth-rate formulas", experience_body())


if __name__ == "__main__":
    main()
