"""Writes the shared tables in src/spec_tables.h from data/ and pret's formulas.

usage: generate_spec_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

LANGUAGE_COLUMNS = ["japanese", "english", "french", "italian", "german", "spanish", "korean"]
GROWTH_RATES = ["medium_fast", "erratic", "fluctuating", "medium_slow", "fast", "slow"]
MAX_LEVEL = 100


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line and not line.startswith("#")]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_spec_tables.py from {source}; do not edit.\n"
    header += '#include "spec_tables.h"\n\n'
    path.write_text(header + body)


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def species_names_body(species_names):
    lines = ["const char *const spec_species_names[SPEC_NAME_LANGUAGE_COUNT][SPEC_SPECIES_NAME_COUNT] = {"]
    for language in LANGUAGE_COLUMNS:
        lines.append(f"    [SPEC_LANGUAGE_{language.upper()}] = {{")
        for row in species_names:
            lines.append(f"        [{row['national']}] = {c_string(row[language])},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def growth_rate_enum(name):
    return "SPEC_GROWTH_RATE_" + name.upper()


def experience_at_level(growth_rate, n):
    # pret's experience_tables.h lists levels 0 and 1 outright and uses these formulas from level 2.
    if n <= 1:
        return n
    cube = n * n * n
    if growth_rate == "medium_fast":
        return cube
    if growth_rate == "erratic":
        if n <= 50:
            return (100 - n) * cube // 50
        if n <= 68:
            return (150 - n) * cube // 100
        if n <= 98:
            return ((1911 - 10 * n) // 3) * cube // 500
        return (160 - n) * cube // 100
    if growth_rate == "fluctuating":
        if n <= 15:
            return ((n + 1) // 3 + 24) * cube // 50
        if n <= 36:
            return (n + 14) * cube // 50
        return ((n // 2) + 32) * cube // 50
    if growth_rate == "medium_slow":
        return (6 * cube) // 5 - 15 * n * n + 100 * n - 140
    if growth_rate == "fast":
        return (4 * cube) // 5
    if growth_rate == "slow":
        return (5 * cube) // 4
    raise ValueError(growth_rate)


def experience_body():
    lines = ["const uint32_t spec_experience[SPEC_GROWTH_RATE_COUNT][SPEC_LEVEL_COUNT] = {"]
    for growth_rate in GROWTH_RATES:
        values = [str(experience_at_level(growth_rate, level)) for level in range(MAX_LEVEL + 1)]
        lines.append(f"    [{growth_rate_enum(growth_rate)}] = {{")
        for start in range(0, len(values), 10):
            lines.append("        " + ", ".join(values[start : start + 10]) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species_names = read_tsv(data_directory / "species_names.tsv")
    write_c_file(output_directory / "species_names.c", "data/species_names.tsv", species_names_body(species_names))
    write_c_file(output_directory / "experience.c", "pret's growth-rate formulas", experience_body())


if __name__ == "__main__":
    main()
