"""Writes the 3DS tables in src/3ds/tables.h from data/3ds/.

usage: generate_3ds_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

STAT_COLUMNS = ["hp", "attack", "defense", "speed", "special_attack", "special_defense"]
POCKET_COLUMNS = ["x_y", "omega_ruby_alpha_sapphire", "sun_moon", "ultra_sun_ultra_moon"]
CHINESE_COLUMNS = ["chinese_simplified", "chinese_traditional"]
GENERATIONS = {"6": "gen6", "7": "gen7"}
ITEM_COUNT = 960


def read_tsv(path):
    lines = [line for line in path.read_text(encoding="utf-8").splitlines() if line]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_3ds_tables.py from {source}; do not edit.\n"
    header += '#include "3ds/tables.h"\n\n'
    path.write_text(header + body, encoding="utf-8")


def growth_rate_enum(name):
    return "SPEC_GROWTH_RATE_" + name.upper()


def species_data_of(row):
    stats = ", ".join(row[column] for column in STAT_COLUMNS)
    return f"{{{{{stats}}}, {row['gender_ratio']}, {growth_rate_enum(row['growth_rate'])}}}"


def species_body(species):
    lines = []
    for generation, prefix in GENERATIONS.items():
        rows = [row for row in species if row["generation"] == generation]
        lines.append(f"const spec_3ds_species_data_t spec_3ds_{prefix}_species_data[SPEC_3DS_SPECIES_COUNT] = {{")
        for row in rows:
            if row["form"] == "0":
                lines.append(f"    [{row['national']}] = {species_data_of(row)},")
        lines.append("};\n")
        lines.append(f"const spec_3ds_form_data_t spec_3ds_{prefix}_form_data[] = {{")
        for row in rows:
            if row["form"] != "0":
                lines.append(f"    {{{row['national']}, {row['form']}, {species_data_of(row)}}},")
        lines.append("};")
        lines.append(f"const size_t spec_3ds_{prefix}_form_data_count =")
        lines.append(f"    sizeof spec_3ds_{prefix}_form_data / sizeof spec_3ds_{prefix}_form_data[0];\n")
    return "\n".join(lines)


def pocket_value(cell):
    return "SPEC_3DS_NO_POCKET" if cell == "-" else "SPEC_3DS_POCKET_" + cell.upper()


# Every number gets a row, since pocket 0 is a pocket: the ones the data leaves out have none.
def items_body(items):
    rows = {int(row["item"]): row for row in items}
    lines = ["const spec_3ds_item_data_t spec_3ds_items[SPEC_3DS_ITEM_COUNT] = {"]
    for item in range(ITEM_COUNT):
        row = rows.get(item, {column: "-" for column in POCKET_COLUMNS})
        pockets = ", ".join(pocket_value(row[column]) for column in POCKET_COLUMNS)
        lines.append(f"    [{item}] = {{{{{pockets}}}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def glyphs_body(glyphs):
    lines = ["const char16_t spec_3ds_chinese_glyphs[SPEC_3DS_CHINESE_GLYPH_COUNT] = {"]
    for row in glyphs:
        lines.append(f"    [0x{row['unit']} - SPEC_3DS_FIRST_CHINESE_GLYPH] = 0x{ord(row['character']):04X},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def chinese_names_body(names):
    lines = [
        "const uint16_t spec_3ds_chinese_species_names[2][SPEC_3DS_SPECIES_COUNT]"
        "[SPEC_3DS_CHINESE_NAME_SIZE] = {"
    ]
    for column in CHINESE_COLUMNS:
        lines.append("    {")
        for row in names:
            units = ", ".join("0x" + unit for unit in row[column].split())
            lines.append(f"        [{row['national']}] = {{{units}}},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species = read_tsv(data_directory / "species.tsv")
    items = read_tsv(data_directory / "items.tsv")
    glyphs = read_tsv(data_directory / "chinese_glyphs.tsv")
    names = read_tsv(data_directory / "chinese_species_names.tsv")
    write_c_file(output_directory / "species_data.c", "data/3ds/species.tsv", species_body(species))
    write_c_file(output_directory / "items.c", "data/3ds/items.tsv", items_body(items))
    chinese = glyphs_body(glyphs) + "\n" + chinese_names_body(names)
    source = "data/3ds/chinese_glyphs.tsv and chinese_species_names.tsv"
    write_c_file(output_directory / "chinese.c", source, chinese)


if __name__ == "__main__":
    main()
