"""Writes the Game Boy tables in src/gb/tables.h from data/gb/.

usage: generate_gb_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

STAT_COLUMNS = ["hp", "attack", "defense", "speed", "special"]
CHARMAP_COLUMNS = ["english", "french_german", "italian_spanish", "japanese"]


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line and not line.startswith("#")]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_gb_tables.py from {source}; do not edit.\n"
    header += '#include "gb/tables.h"\n\n'
    path.write_text(header + body)


def growth_rate_enum(name):
    return "SPEC_GROWTH_RATE_" + name.upper()


def species_national_body(species):
    lines = ["const uint16_t spec_gb_national_of_species[SPEC_GB_SPECIES_INDEX_COUNT] = {"]
    for row in species:
        lines.append(f"    [{row['index']}] = {row['national']},")
    lines.append("};\n")
    lines.append("const uint8_t spec_gb_species_of_national[SPEC_GB_POKEDEX_SIZE] = {")
    for row in sorted(species, key=lambda row: int(row["national"])):
        lines.append(f"    [{row['national']}] = {row['index']},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def species_data_body(species):
    lines = ["const spec_gb_species_data_t spec_gb_species_data[SPEC_GB_SPECIES_INDEX_COUNT] = {"]
    for row in species:
        stats = ", ".join(row[column] for column in STAT_COLUMNS)
        growth_rate = growth_rate_enum(row["growth_rate"])
        lines.append(f"    [{row['index']}] = {{{{{stats}}}, {growth_rate}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def code_points_of(cell):
    return [int(code.removeprefix("U+"), 16) for code in cell.removeprefix("~").split()]


def character_of(cell, hiragana_cell):
    if cell == "-":
        return None
    code_points = code_points_of(cell) + [0]
    hiragana = 0 if hiragana_cell == "-" else code_points_of(hiragana_cell)[0]
    is_read_only = "true" if cell.startswith("~") else "false"
    return f"{{{{0x{code_points[0]:04X}, 0x{code_points[1]:04X}}}, 0x{hiragana:04X}, {is_read_only}}}"


# Each character or ligature must be written by one byte, so text encodes one way.
def check_charmap_writes_each_once(charmap, column):
    written = [row[column] for row in charmap if row[column] != "-" and not row[column].startswith("~")]
    duplicates = {cell for cell in written if written.count(cell) > 1}
    if duplicates:
        raise ValueError(f"charmap column {column} writes {sorted(duplicates)} with more than one byte")


def charmap_body(charmap, table_prefix):
    lines = []
    for column in CHARMAP_COLUMNS:
        check_charmap_writes_each_once(charmap, column)
        hiragana_column = "japanese_hiragana" if column == "japanese" else None
        lines.append(f"const spec_gb_character_t {table_prefix}_{column}[SPEC_GB_CHARMAP_SIZE] = {{")
        for row in charmap:
            character = character_of(row[column], row[hiragana_column] if hiragana_column else "-")
            if character is not None:
                lines.append(f"    [0x{row['byte']}] = {character},")
        lines.append("};\n")
    return "\n".join(lines)


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def items_body(items):
    lines = ["const char *const spec_gb_item_names[SPEC_GB_ITEM_COUNT] = {"]
    for row in items:
        lines.append(f"    [{row['item']}] = {c_string(row['english'])},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species = read_tsv(data_directory / "species.tsv")
    charmap = read_tsv(data_directory / "charmap.tsv")
    items = read_tsv(data_directory / "items.tsv")
    write_c_file(output_directory / "species_national.c", "data/gb/species.tsv", species_national_body(species))
    write_c_file(output_directory / "species_data.c", "data/gb/species.tsv", species_data_body(species))
    write_c_file(output_directory / "charmap.c", "data/gb/charmap.tsv", charmap_body(charmap, "spec_gb_charmap"))
    write_c_file(output_directory / "items.c", "data/gb/items.tsv", items_body(items))


if __name__ == "__main__":
    main()
