"""Writes the shared tables in src/spec_tables.h from data/.

usage: generate_spec_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line and not line.startswith("#")]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


LANGUAGE_COLUMNS = ["japanese", "english", "french", "italian", "german", "spanish", "korean"]


def species_names_body(species_names):
    lines = ["const char *const spec_species_names[SPEC_NAME_LANGUAGE_COUNT][SPEC_SPECIES_NAME_COUNT] = {"]
    for language in LANGUAGE_COLUMNS:
        lines.append(f"    [SPEC_LANGUAGE_{language.upper()}] = {{")
        for row in species_names:
            lines.append(f"        [{row['national']}] = {c_string(row[language])},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species_names = read_tsv(data_directory / "species_names.tsv")
    header = "// Generated by tools/generate_spec_tables.py from data/species_names.tsv; do not edit.\n"
    header += '#include "spec_tables.h"\n\n'
    (output_directory / "species_names.c").write_text(header + species_names_body(species_names))


if __name__ == "__main__":
    main()
