"""Writes the GBA tables in src/gba/tables.h from data/gba/.

usage: generate_gba_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

GROWTH_RATES = ["medium_fast", "erratic", "fluctuating", "medium_slow", "fast", "slow"]
STAT_COLUMNS = ["hp", "attack", "defense", "speed", "special_attack", "special_defense"]
CHARMAP_COLUMNS = ["japanese", "international", "french", "german"]
POCKET_COLUMNS = ["ruby_sapphire", "emerald", "firered_leafgreen"]
MAX_LEVEL = 100


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line and not line.startswith("#")]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_gba_tables.py from {source}; do not edit.\n"
    header += '#include "gba/tables.h"\n\n'
    path.write_text(header + body)


def growth_rate_enum(name):
    return "SPEC_GBA_GROWTH_RATE_" + name.upper()


def species_national_body(species):
    lines = ["const uint16_t spec_gba_national_of_species[SPEC_GBA_SPECIES_INDEX_COUNT] = {"]
    for row in species:
        lines.append(f"    [{row['index']}] = {row['national']}, // {row['name']}")
    lines.append("};\n")
    lines.append("const uint16_t spec_gba_species_of_national[SPEC_GBA_NATIONAL_COUNT] = {")
    for row in sorted(species, key=lambda row: int(row["national"])):
        lines.append(f"    [{row['national']}] = {row['index']}, // {row['name']}")
    lines.append("};")
    return "\n".join(lines) + "\n"


def species_data_body(species):
    lines = ["const spec_gba_species_data_t spec_gba_species_data[SPEC_GBA_SPECIES_INDEX_COUNT] = {"]
    for row in species:
        stats = ", ".join(row[column] for column in STAT_COLUMNS)
        growth_rate = growth_rate_enum(row["growth_rate"])
        gender_ratio = row["gender_ratio"]
        lines.append(f"    [{row['index']}] = {{{{{stats}}}, {growth_rate}, {gender_ratio}}}, // {row['name']}")
    lines.append("};")
    return "\n".join(lines) + "\n"


def experience_at_level(growth_rate, n):
    # pret's experience_tables.h lists levels 0 and 1 outright and uses these formulas from level 2.
    if n <= 1:
        return n
    cube = n * n * n
    if growth_rate == "medium_fast":
        return cube
    if growth_rate == "erratic":
        if n <= 50:
            return (100 - n) * cube // 50
        if n <= 68:
            return (150 - n) * cube // 100
        if n <= 98:
            return ((1911 - 10 * n) // 3) * cube // 500
        return (160 - n) * cube // 100
    if growth_rate == "fluctuating":
        if n <= 15:
            return ((n + 1) // 3 + 24) * cube // 50
        if n <= 36:
            return (n + 14) * cube // 50
        return ((n // 2) + 32) * cube // 50
    if growth_rate == "medium_slow":
        return (6 * cube) // 5 - 15 * n * n + 100 * n - 140
    if growth_rate == "fast":
        return (4 * cube) // 5
    if growth_rate == "slow":
        return (5 * cube) // 4
    raise ValueError(growth_rate)


def experience_body():
    lines = ["const uint32_t spec_gba_experience[SPEC_GBA_GROWTH_RATE_COUNT][SPEC_GBA_LEVEL_COUNT] = {"]
    for growth_rate in GROWTH_RATES:
        values = [str(experience_at_level(growth_rate, level)) for level in range(MAX_LEVEL + 1)]
        lines.append(f"    [{growth_rate_enum(growth_rate)}] = {{")
        for start in range(0, len(values), 10):
            lines.append("        " + ", ".join(values[start : start + 10]) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def code_point_of(cell):
    return 0 if cell == "-" else int(cell.removeprefix("U+"), 16)


def check_charmap_has_no_duplicates(charmap, column):
    code_points = [code_point_of(row[column]) for row in charmap if row[column] != "-"]
    duplicates = {code_point for code_point in code_points if code_points.count(code_point) > 1}
    if duplicates:
        raise ValueError(f"charmap column {column} repeats {sorted(duplicates)}")


def charmap_body(charmap):
    lines = []
    for column in CHARMAP_COLUMNS:
        check_charmap_has_no_duplicates(charmap, column)
        lines.append(f"const uint16_t spec_gba_charmap_{column}[SPEC_GBA_CHARMAP_SIZE] = {{")
        for row in charmap:
            lines.append(f"    [0x{row['byte']}] = 0x{code_point_of(row[column]):04X},")
        lines.append("};\n")
    return "\n".join(lines)


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_string_or_null(cell):
    return "nullptr" if cell == "-" else c_string(cell)


def pocket_value(cell):
    return "SPEC_GBA_NO_POCKET" if cell == "-" else "SPEC_GBA_POCKET_" + cell.upper()


def items_body(items):
    lines = ["const spec_gba_item_data_t spec_gba_items[SPEC_GBA_ITEM_COUNT] = {"]
    for row in items:
        pockets = ", ".join(pocket_value(row[column]) for column in POCKET_COLUMNS)
        is_important = "true" if row["is_important"] == "yes" else "false"
        names = ", ".join(c_string_or_null(row[column]) for column in ["english", "german"])
        lines.append(f"    [{row['item']}] = {{{names}, {pockets}, {is_important}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species = read_tsv(data_directory / "species.tsv")
    charmap = read_tsv(data_directory / "charmap.tsv")
    items = read_tsv(data_directory / "items.tsv")
    write_c_file(output_directory / "species_national.c", "data/gba/species.tsv", species_national_body(species))
    write_c_file(output_directory / "species_data.c", "data/gba/species.tsv", species_data_body(species))
    write_c_file(output_directory / "experience.c", "pret's growth-rate formulas", experience_body())
    write_c_file(output_directory / "charmap.c", "data/gba/charmap.tsv", charmap_body(charmap))
    write_c_file(output_directory / "items.c", "data/gba/items.tsv", items_body(items))


if __name__ == "__main__":
    main()
