"""Writes the NDSi tables in src/ndsi/tables.h from data/ndsi/.

usage: generate_ndsi_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

STAT_COLUMNS = ["hp", "attack", "defense", "speed", "special_attack", "special_defense"]
POCKET_COLUMNS = ["black_white", "black2_white2"]
TYPE_COLUMNS = ["type_1", "type_2"]
ABILITY_COLUMNS = ["ability_1", "ability_2", "hidden_ability"]


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_ndsi_tables.py from {source}; do not edit.\n"
    header += '#include "ndsi/tables.h"\n\n'
    path.write_text(header + body)


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def stats_of(row):
    return ", ".join(row[column] for column in STAT_COLUMNS)


# "-" is every game, which the first game type stands for.
def from_game_enum(from_game):
    return "SPEC_GAME_TYPE_" + ("red_blue" if from_game == "-" else from_game).upper()


def species_data_of(row):
    types = ", ".join("SPEC_TYPE_" + row[column].upper() for column in TYPE_COLUMNS)
    abilities = ", ".join(row[column] for column in ABILITY_COLUMNS)
    counts = f"{row['gender_ratio']}, {row['egg_cycles']}, {row['base_friendship']}"
    growth_rate = "SPEC_GROWTH_RATE_" + row["growth_rate"].upper()
    return f"{{{stats_of(row)}}}, {{{types}}}, {{{abilities}}}, {counts}, {growth_rate}"


def species_data_body(species):
    lines = ["const spec_ndsi_species_row_t spec_ndsi_species_rows[] = {"]
    for row in species:
        key = f"{row['national']}, {row['form']}, {from_game_enum(row['from_game'])}"
        lines.append(f"    {{{key}, {{{species_data_of(row)}}}}},")
    lines.append("};\n")
    lines.append("const size_t spec_ndsi_species_row_count =")
    lines.append("    sizeof spec_ndsi_species_rows / sizeof spec_ndsi_species_rows[0];")
    return "\n".join(lines) + "\n"



def pocket_value(cell):
    return "SPEC_NDSI_NO_POCKET" if cell == "-" else "SPEC_NDSI_POCKET_" + cell.upper()


def items_body(items):
    lines = ["const spec_ndsi_item_data_t spec_ndsi_items[SPEC_NDSI_ITEM_COUNT] = {"]
    for row in items:
        pockets = ", ".join(pocket_value(row[column]) for column in POCKET_COLUMNS)
        lines.append(f"    [{row['item']}] = {{{c_string(row['english'])}, {pockets}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species = read_tsv(data_directory / "species.tsv")
    items = read_tsv(data_directory / "items.tsv")
    write_c_file(output_directory / "species_data.c", "data/ndsi/species.tsv", species_data_body(species))
    write_c_file(output_directory / "items.c", "data/ndsi/items.tsv", items_body(items))


if __name__ == "__main__":
    main()
