"""Writes the NDSi tables in src/ndsi/tables.h from data/ndsi/.

usage: generate_ndsi_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

STAT_COLUMNS = ["hp", "attack", "defense", "speed", "special_attack", "special_defense"]
POCKET_COLUMNS = ["black_white", "black2_white2"]


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line and not line.startswith("#")]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_ndsi_tables.py from {source}; do not edit.\n"
    header += '#include "ndsi/tables.h"\n\n'
    path.write_text(header + body)


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def stats_of(row):
    return ", ".join(row[column] for column in STAT_COLUMNS)


def species_data_body(species):
    lines = ["const spec_ndsi_species_data_t spec_ndsi_species_data[SPEC_NDSI_SPECIES_COUNT] = {"]
    for row in species:
        if row["form"] != "0":
            continue
        growth_rate = "SPEC_GROWTH_RATE_" + row["growth_rate"].upper()
        lines.append(f"    [{row['national']}] = {{{{{stats_of(row)}}}, {growth_rate}, {row['gender_ratio']}}},")
    lines.append("};\n")
    lines.append("const spec_ndsi_form_data_t spec_ndsi_form_data[SPEC_NDSI_FORM_DATA_COUNT] = {")
    for row in species:
        if row["form"] == "0":
            continue
        lines.append(f"    {{{row['national']}, {row['form']}, {{{stats_of(row)}}}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"



def pocket_value(cell):
    return "SPEC_NDSI_NO_POCKET" if cell == "-" else "SPEC_NDSI_POCKET_" + cell.upper()


def items_body(items):
    lines = ["const spec_ndsi_item_data_t spec_ndsi_items[SPEC_NDSI_ITEM_COUNT] = {"]
    for row in items:
        pockets = ", ".join(pocket_value(row[column]) for column in POCKET_COLUMNS)
        lines.append(f"    [{row['item']}] = {{{c_string(row['english'])}, {pockets}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species = read_tsv(data_directory / "species.tsv")
    items = read_tsv(data_directory / "items.tsv")
    write_c_file(output_directory / "species_data.c", "data/ndsi/species.tsv", species_data_body(species))
    write_c_file(output_directory / "items.c", "data/ndsi/items.tsv", items_body(items))


if __name__ == "__main__":
    main()
