"""Writes the NDS tables in src/nds/tables.h from data/nds/.

usage: generate_nds_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

STAT_COLUMNS = ["hp", "attack", "defense", "speed", "special_attack", "special_defense"]
POCKET_COLUMNS = ["diamond_pearl", "platinum", "heartgold_soulsilver"]


def read_tsv(path):
    lines = [line for line in path.read_text().splitlines() if line and not line.startswith("#")]
    header = lines[0].split("\t")
    return [dict(zip(header, line.split("\t"))) for line in lines[1:]]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_nds_tables.py from {source}; do not edit.\n"
    header += '#include "nds/tables.h"\n\n'
    path.write_text(header + body)


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def stats_of(row):
    return ", ".join(row[column] for column in STAT_COLUMNS)


def species_data_body(species):
    lines = ["const spec_nds_species_data_t spec_nds_species_data[SPEC_NDS_SPECIES_COUNT] = {"]
    for row in species:
        if row["form"] != "0":
            continue
        growth_rate = "SPEC_GROWTH_RATE_" + row["growth_rate"].upper()
        lines.append(f"    [{row['national']}] = {{{{{stats_of(row)}}}, {growth_rate}, {row['gender_ratio']}}},")
    lines.append("};\n")
    lines.append("const spec_nds_form_data_t spec_nds_form_data[SPEC_NDS_FORM_DATA_COUNT] = {")
    for row in species:
        if row["form"] == "0":
            continue
        lines.append(f"    {{{row['national']}, {row['form']}, {{{stats_of(row)}}}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def charmap_body(charmap):
    code_points = [int(row["character"].removeprefix("U+"), 16) for row in charmap]
    duplicates = {code_point for code_point in code_points if code_points.count(code_point) > 1}
    # Only the sex symbols have two codes: full width for Japanese, half width otherwise.
    if duplicates != {0x2640, 0x2642}:
        raise ValueError(f"charmap repeats {sorted(duplicates)}")
    lines = ["const uint16_t spec_nds_charmap[SPEC_NDS_CHARMAP_SIZE] = {"]
    for row in charmap:
        lines.append(f"    [0x{row['code']}] = 0x{int(row['character'].removeprefix('U+'), 16):04X},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def pocket_value(cell):
    return "SPEC_NDS_NO_POCKET" if cell == "-" else "SPEC_NDS_POCKET_" + cell.upper()


def items_body(items):
    lines = ["const spec_nds_item_data_t spec_nds_items[SPEC_NDS_ITEM_COUNT] = {"]
    for row in items:
        pockets = ", ".join(pocket_value(row[column]) for column in POCKET_COLUMNS)
        lines.append(f"    [{row['item']}] = {{{c_string(row['english'])}, {pockets}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species = read_tsv(data_directory / "species.tsv")
    charmap = read_tsv(data_directory / "charmap.tsv")
    items = read_tsv(data_directory / "items.tsv")
    write_c_file(output_directory / "species_data.c", "data/nds/species.tsv", species_data_body(species))
    write_c_file(output_directory / "charmap.c", "data/nds/charmap.tsv", charmap_body(charmap))
    write_c_file(output_directory / "items.c", "data/nds/items.tsv", items_body(items))


if __name__ == "__main__":
    main()
