"""Writes the Game Boy Color tables in src/gbc/tables.h from data/gbc/.

usage: generate_gbc_tables.py DATA_DIRECTORY OUTPUT_DIRECTORY
"""

import sys
from pathlib import Path

from generate_gb_tables import charmap_body, growth_rate_enum, item_names_body, read_tsv

STAT_COLUMNS = ["hp", "attack", "defense", "speed", "special_attack", "special_defense"]
POCKET_COLUMNS = ["gold_silver_pocket", "crystal_pocket"]
ITEM_NAME_COLUMNS = ["japanese", "english", "spanish", "korean"]


def write_c_file(path, source, body):
    header = f"// Generated by tools/generate_gbc_tables.py from {source}; do not edit.\n"
    header += '#include "gbc/tables.h"\n\n'
    path.write_text(header + body)


def species_data_body(species):
    lines = ["const spec_gbc_species_data_t spec_gbc_species_data[SPEC_GBC_POKEDEX_SIZE] = {"]
    for row in species:
        stats = ", ".join(row[column] for column in STAT_COLUMNS)
        growth_rate = growth_rate_enum(row["growth_rate"])
        lines.append(f"    [{row['national']}] = {{{{{stats}}}, {growth_rate}, {row['gender_ratio']}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def pocket_value(cell):
    return "SPEC_GBC_NO_POCKET" if cell == "-" else "SPEC_GBC_POCKET_" + cell.upper()


def items_body(items):
    lines = ["const spec_gbc_item_data_t spec_gbc_items[SPEC_GBC_ITEM_COUNT] = {"]
    for row in items:
        pockets = ", ".join(pocket_value(row[column]) for column in POCKET_COLUMNS)
        machine = "0" if row["machine"] == "-" else row["machine"]
        is_mail = "true" if row["is_mail"] == "yes" else "false"
        lines.append(f"    [{row['item']}] = {{{pockets}, {machine}, {is_mail}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data_directory = Path(sys.argv[1])
    output_directory = Path(sys.argv[2])
    output_directory.mkdir(parents=True, exist_ok=True)
    species = read_tsv(data_directory / "species.tsv")
    charmap = read_tsv(data_directory / "charmap.tsv")
    items = read_tsv(data_directory / "items.tsv")
    write_c_file(output_directory / "species_data.c", "data/gbc/species.tsv", species_data_body(species))
    write_c_file(output_directory / "charmap.c", "data/gbc/charmap.tsv", charmap_body(charmap, "spec_gbc_charmap"))
    names = item_names_body(items, "spec_gbc_item_names", "SPEC_GBC_ITEM_COUNT", ITEM_NAME_COLUMNS)
    write_c_file(output_directory / "items.c", "data/gbc/items.tsv", items_body(items) + "\n" + names)


if __name__ == "__main__":
    main()
