#ifndef SPEC_TABLES_H
#define SPEC_TABLES_H

#include <stddef.h>

#include "spec.h"

// Generated by tools/generate_spec_tables.py.

constexpr size_t SPEC_SPECIES_NAME_COUNT = 808;
constexpr size_t SPEC_NAME_LANGUAGE_COUNT = SPEC_LANGUAGE_KOREAN + 1;

extern const char *const spec_species_names[SPEC_NAME_LANGUAGE_COUNT][SPEC_SPECIES_NAME_COUNT];

#endif
