#ifndef SPEC_TABLES_H
#define SPEC_TABLES_H

#include <stddef.h>

// Generated by tools/generate_spec_tables.py.

constexpr size_t SPEC_SPECIES_NAME_COUNT = 808;

extern const char *const spec_species_names[SPEC_SPECIES_NAME_COUNT];

#endif
